name: deploy

on:
  push:
    branches:
      - add-ci-cd
      - main

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Publish image + deploy
        run: make deploy
